add file storage, data compress/decompress, /api/shortener endpoint and logger
sheinsviatoslav/shortener pull request #10
Opened 2024-11-21 16:42 UTC by sheinsviatoslav

2024-11-22 10:19 UTC, edylcrm requested changes

2024-11-22 10:19 UTC, edylcrm commented on internal/handlers/createurl/handler.go
> +	for _, urlItem := range items {
Почему именно slice, а не map? Каждый раз поиск будет выполняться за O(n), можно сделать за O(1)

2024-11-22 10:19 UTC, edylcrm commented on internal/handlers/createurl/handler.go
> +		if fileReader != nil {
Всю работу с файлом лучше вынести в отдельную структуру что-то вроде fileStorage в котором будет вся логика по работе с ним. Это позволит в дальнейшем сделать общий интерфейс под все типы хранилища

2024-11-22 10:19 UTC, edylcrm commented on internal/handlers/geturl/handler.go
> +	if _, err := os.Stat(*config.FileStoragePath); err == nil {
Можно делать ранний return и не писать if внутри if, код читается тяжело

2024-11-22 10:19 UTC, edylcrm commented on internal/handlers/geturl/handler.go
> +	for _, urlItem := range items {
Такая же проблема с О(n)

2024-11-22 10:19 UTC, edylcrm commented on internal/handlers/shorten/handler.go
> +	if !isURLExists {
Повторяется в другом хендлере, может вынести куда-то бизнес логику и использовать ее везде?

2024-11-23 12:42 UTC, sheinsviatoslav commented on internal/handlers/geturl/handler.go
> +	for _, urlItem := range items {
здесь не очень понял как O(1), тут же мы по значению должны ключ найти

2024-11-25 17:55 UTC, sheinsviatoslav commented on internal/handlers/shorten/handler.go
> +	if !isURLExists {
вынес что можно

2024-11-25 17:55 UTC, sheinsviatoslav commented on internal/handlers/geturl/handler.go
> +	if _, err := os.Stat(*config.FileStoragePath); err == nil {
вынес это в storage

2024-11-25 17:56 UTC, sheinsviatoslav commented on internal/handlers/createurl/handler.go
> +	for _, urlItem := range items {
переделал на map

2024-11-25 17:57 UTC, sheinsviatoslav commented on internal/handlers/createurl/handler.go
> +		if fileReader != nil {
вынес в функции, только не уверен что правильно сделал

2024-11-26 08:23 UTC, edylcrm commented on internal/handlers/geturl/handler.go
> +	for _, urlItem := range items {
Можно сделать две map

2024-11-26 08:23 UTC, edylcrm approved these changes

2024-11-26 13:27 UTC, merged