add shortener server
sheinsviatoslav/shortener pull request #6
Opened 2024-10-31 13:38 UTC by sheinsviatoslav

2024-11-01 07:39 UTC, edylcrm requested changes

2024-11-01 07:39 UTC, edylcrm commented on internal/handlers/createurl/handler.go
> +	w.Header().Set("Content-Type", "text/plain")
defer req.Body.Close() еще можно добавить

2024-11-01 07:39 UTC, edylcrm commented on internal/storage/storage.go
> +var URLMap = map[string]string{}
Глобальные переменные которые могут использоваться везде я бы предложил не делать и заменить это на структуру вида:
```
type Storage struct {
    data map[string]string
    m sync.Mutex
}

func (s *Storage) get(key string) (string, error)

func (s *Storage) set(key string, value string) error
```
И использовать только там где необходимо

2024-11-02 21:04 UTC, sheinsviatoslav commented on internal/handlers/createurl/handler.go
> +	w.Header().Set("Content-Type", "text/plain")
а разве это автоматически не делается? в уроке "Создание HTTP-сервера" есть инфа, что вызывать не надо: ```Тело запроса хранится в поле Body io.ReadCloser и читается стандартными методами — например, body, err := io.ReadAll(req.Body). Вызывать Body.Close() не нужно, так как это автоматически делает сервер.```

2024-11-08 08:26 UTC, sheinsviatoslav commented on internal/storage/storage.go
> +var URLMap = map[string]string{}
предлагаю сразу все переделать уже когда появится БД

2024-11-13 14:12 UTC, merged